# .github/workflows/azure-static-web-apps.yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master   # or main, match your default branch
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build Storybook
        # Storybook 7+: `npx storybook build` also works
        run: npm run build-storybook

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # We already built, so skip Oryx and just deploy the artifacts:
          skip_app_build: true
          app_location: "/"                      # repo root (doesn't matter when skipping build)
          app_artifact_location: "storybook-static"  # <-- where Storybook outputs index.html
          production_branch: "master"            # match your default branch
