# .github/workflows/azure-static-web-apps-thankful-mud-05ce3700f.yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # If you ever keep big artifacts in LFS:
          # lfs: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy prebuilt Storybook to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_05CE3700F }}
          action: upload
          # We already built to storybook-static/, so deploy that folder as the "app"
          app_location: storybook-static
          skip_app_build: true
          api_location: ""
          data_api_location: ""
